@startuml

hide empty members
skinparam groupInheritance 2

skinparam linetype polyline




class Die

package "Game Board" {
    class Board
    class "<<abstract>>\nSquare" as Square
        class Amusement
        class Restrooms
        class Start
        class Railroad
        class Chance
        class PennyBag
        class PayFor
}

package Logic {
    class Bank
    class GameController
    class PositionHandler
    class ActionHandler
}

class Deck
class ChanceCard
class Player
class "<<singleton>>\nLanguage" as Language

GameController -down- Board
GameController -- Die

GameController -left- ActionHandler
    ActionHandler -left- Bank
    ActionHandler -- Deck
        Deck -left ChanceCard
GameController -right- PositionHandler

Player -down- ActionHandler
Player -down- PositionHandler
Player -down- GameController
Player -down- Bank

Board -- Square
Square <|-- Restrooms
Square <|-- Amusement
Square <|-- Railroad
Square <|-- PayFor
Square <|-- PennyBag
Square <|-- Start
Square <|-- Chance


@enduml