@startuml

hide empty members
skinparam groupInheritance 2

class "Monopoly Junior" as Game
class Die

package "Game Board" {
    class Board

    class "<<abstract>>\nSquare" as Square
        class Amusement
        class Restrooms
        class Start
        class Railroad
        class Chance
        class PennyBag
        class PayFor
}

package Logic {
    class Bank
    class GameController
    class PlayerHandler
    class PositionHandler
    class SquareActionHandler
}



class Deck
class ChanceCard
class Player
class "<<singleton>>\nLanguage" as Language

Game -up- Die
Game -right- Deck
    Deck *-right- ChanceCard
Game -left- Player
Game -down- Board
    Board *-down- Square
    Square <|-- Restrooms
    Square <|-- Amusement
    Square <|-- Railroad
    Square <|-- PayFor
    Square <|-- PennyBag
    Square <|-- Start
    Square <|-- Chance

class Game {
    -players: Player[]
    -currentPlayer: Player
    -board: Board[]
    -deck: Deck
    -die: Die
    -hasWinner: boolean
    -MIN_NR_OF_PLAYERS: int
    -MAX_NR_OF_PLAYERS: int
    -START_MONEY: int
    -RESTOROOM_POSITION: int
    -MOVING_PAST_START: int
    -BOARD_SIZE: int
    -PENNYBAG_POSITION: int

    -handleField(int position): void
    -handleChance(): void
    +setupGame(): void
    +playGame(): void
    +initializePlayers(int numOfPlayers): void
    +takeTurn(): void
    +chancePlayer(): void
    +updatePosition(int moveSpaces): void
    +hasPassStart(int prevPos, int endPos, boolean goingToRestrooms) : void
    +pay(int amount): void
    +pay(Player to, int amount): void
    +paymentPossible(Player player, int amount): boolean
    +decideAndAnnounceWinner(): void

}

class Board {
    -squares: Square[]
    -pennyBagPosition: int

    +getSquare(): Square
    +addBooth(Player, position:int) : void
    +removeBooth(position): void
    +hasMonopoly(): boolean

    -readCSV(): void
}

class Square {
    -name: String
    -position: int
    -Effect?!
}

class Die {
    -faceValue: int
    -nrOfSides: int

    +roll(): void
}

class Player {
    -color: Color:
    -name: String
    -position: int
    -balance: int
    -boothsOnHand: int
    -goingToRestroom: boolean

    +hasBooth(): boolean
    +updateBalance(int update): void
    +useOneBooth(): void
    +setupStartBalance(int startMoney): void
}

class Deck {
    -chanceCardDeck: ChanceCard[]
    -drawCardCount: int

    +pullCard(): ChanceCard
    +shuffleDeck(): void
}
class ChanceCard {
    -chanceCardText: String
    -color: String
    -amountToPay: int
    -destination: int

}
class Amusement {
    -boothOwner: Player
    -color: String
    -price: int

}

@enduml