@startuml

hide empty members
skinparam groupInheritance 2

class Die

package "Game Board" {
    class Board
    class "<<abstract>>\nSquare" as Square
        class Amusement
        class Restrooms
        class Start
        class Railroad
        class Chance
        class PennyBag
        class PayFor
}

package Logic {
    class Bank
    class GameController
    class PlayerHandler
    class PositionHandler
    class SquareActionHandler
}

class Deck
class ChanceCard
class Player
class "<<singleton>>\nLanguage" as Language

Deck *- ChanceCard
Board *-down Square
Square <|-- Restrooms
Square <|-- Amusement
Square <|-- Railroad
Square <|-- PayFor
Square <|-- PennyBag
Square <|-- Start
Square <|-- Chance

GameController -up- PositionHandler
GameController -up- PlayerHandler
GameController -up- Die
GameController -left- SquareActionHandler
GameController -left- Deck
GameController -down- Board

PlayerHandler -up- Player
SquareActionHandler -up- Bank
SquareActionHandler -- Board
Bank -up- Player
PositionHandler -up- Player


@enduml