@startuml
'https://plantuml.com/class-diagram

class "Monopoly_Junior" as Game
class Terning
class Spillebræt
class Felt
class Bunken
class Kort
class Spiller
class Konto
class Billetboder
class SpilleBrik

Game --|> Terning
Game --|> Bunken
Game --|> Spiller
Game --|> Spillebræt
Spillebræt --|> Felt
Spiller --|> Billetboder
Spiller --|> Konto
Spiller --|> SpilleBrik
Bunken --|> Kort

class Game {
    -numberOfPlayers
    -currentPlayer
}

class Terning {
    -faceValue: int
    -nrOfSides: int
    +rollDie(): void
    +getFaceValue(): int
}

class Spillebræt {
    -antalFelter
    +getField()
}

class Felt {
    -fieldName: String
    -effectText: String
    -pris: int
    -ejer: int
    -position: int

    +assignToken(): void
    +toString(): String

}

class Kort {

}

'opdaterBalanse() er lavet som boolean, for at kunne returnere hvis en spiller går bankerot'
class Konto {
    -balanse: int
    +opdaterBalanse(): boolean
    +getBalanse(): int
}

class Bunken {
    -antalKort: int
    -shuffle(): void

}

class Spiller {
    -nr: int
}

class SpilleBrik {
    -position
    +flytSpiller(): void
    +setPosition(): void
}

'assignToken er lavet som boolean return i tilfælde af at der ikke er flere tokens'
class Billetboder {
    -bodNr: static int
    -positionOnBoard: int
    +assignToken(): boolean
}





@enduml