@startuml
'https://plantuml.com/object-diagram

object Deck
object Player
object Die
object Language
object "Monopoly Junior" as game
object "Board" as board
object Square
object "Chance card" as chance

Die : FaceValue
Player : Name
Player : Position
Player : Balance
Player : Color


Square : Type
Square : Owner
Square : Position

chance : Text
chance : color
chance : amounttopay
chance : destination

board : pennyBagPosition





game          "1   "      -r-   "1   "          Deck: Is played with >
board         "1"       -d-   "32"                Square: Is played with >
game          "1"        -d-   "1"                 board: Is played on >
game          "1   "      -l   "2..4 "            Player : Plays <
game           "1"        -u-   "1 "                Die: Is played with >
chance         "24  "     -l-   " 1  "            Deck: Holds <



@enduml