@startuml
'https://plantuml.com/object-diagram

object billetboder{
}
object Spiller
object Terning
object Sprog
object MonopolyJuniorspil
object konto
object Spillerplade
object Felt
object Chancekort

billetboder "48       " -- "1          " MonopolyJuniorspil
Sprog "1..*              " --"1 " MonopolyJuniorspil
Felt "24" -- "1" Spillerplade
Spillerplade "1" -- "1" MonopolyJuniorspil
Spiller "1" -- "1" konto
Spiller "4" -- "1             " MonopolyJuniorspil
Terning "1" -- "1" MonopolyJuniorspil
Chancekort "25      " -- "1" MonopolyJuniorspil


@enduml
