@startuml
'https://plantuml.com/sequence-diagram

autonumber
hide footbox

actor Player #lightyellow
participant ":System" as System
activate Player #lightgreen

Player <-- System: Enter the number of players
Player -> System: Input the number of players

loop all players
    Player <-- System : Enter the player's name
    Player -> System : Input player's name
end

loop until a player has lost
    Player <-- System: Asking to throw die
    Player -> System: Player throw's die
    Player <-- System: Updated game board

end

Player <-- System: End game

@enduml